version: '3.8'

services:
  # MySQL база данных
  mysql:
    image: ghcr.io/aleksandr-polskoy/fms/mysql:latest
    container_name: fms_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-fms_db}
      MYSQL_USER: ${MYSQL_USER:-fms_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-fms_password}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - fms_network

  # PHP Backend (Laravel)
  backend:
    image: ghcr.io/aleksandr-polskoy/fms/backend:latest
    container_name: fms_backend
    restart: unless-stopped
    environment:
      APP_NAME: "FMS"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL:-https://ваш-домен.com}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE:-fms_db}
      DB_USERNAME: ${MYSQL_USER:-fms_user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-fms_password}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY:-}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY:-}
      DEEPSEEK_API_URL: https://api.deepseek.com/recommend
    volumes:
      - backend_storage:/var/www/html/storage
    depends_on:
      - mysql
    networks:
      - fms_network

  # Nginx для Backend (внутренний)
  nginx_backend:
    image: nginx:alpine
    container_name: fms_nginx_backend
    restart: unless-stopped
    volumes:
      - ./nginx/backend-domain.conf:/etc/nginx/conf.d/default.conf
      - backend_storage:/var/www/html
    depends_on:
      - backend
    networks:
      - fms_network

  # Frontend (собранный образ)
  frontend:
    image: ghcr.io/aleksandr-polskoy/fms/frontend:latest
    container_name: fms_frontend
    restart: unless-stopped
    networks:
      - fms_network

  # Nginx для Frontend
  nginx_frontend:
    image: nginx:alpine
    container_name: fms_nginx_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - nginx_backend
    networks:
      - fms_network

volumes:
  mysql_data:
  backend_storage:
  frontend_dist:

networks:
  fms_network:
    driver: bridge 